### ISSUE TITLE
publish command under windows system

### ISSUE THREAD

**Issue by VincentAudigier** [adrtod/rchallenge#2]
Dear all,

I faced to the following issue: I aimed at updating the html file of my challenge automatically, but when I executed the command ` Rscript.exe -e rchallenge::publish(...)` in a windows terminal (like it was suggested in the documentation), I received the message :
Erreur : `pandoc version 1.12.3 or higher is required and was not found (see the help page ?rmarkdown::pandoc_available).` Note that using Rstudio, the publish command worked well, but it failed using terminal.

To solve the issue, the following command performed well in my case

`Rscript.exe -e "Sys.setenv(RSTUDIO_PANDOC='C:/Program Files/RStudio/bin/pandoc'); rchallenge::publish('challenge.rmd')"`

Hope this helps!

Best,

V.

**Comment by adrtod** [comment]
Thanks @VincentAudigier !
